export const ACTIVITY_RECORD_TITLE_MAX_LENGTH = 50;

export const ACTIVITY_RECORD_DESCRIPTION_MAX_LENGTH = 500;

export const ACTIVITY_RECORD_DESCRIPTION_COLLAPSED_LINES = 3;

export const ACTIVITY_RECORD_DESCRIPTION_EXPAND_MIN_LENGTH = 120;
